#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-mclust
Version  : 6.0.0
Release  : 61
URL      : https://cran.r-project.org/src/contrib/mclust_6.0.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/mclust_6.0.0.tar.gz
Summary  : Gaussian Mixture Modelling for Model-Based Clustering,
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-mclust-lib = %{version}-%{release}
BuildRequires : buildreq-R

%description
model-based clustering, classification, and density estimation, 
  including Bayesian regularization, dimension reduction for 
  visualisation, and resampling-based inference.

%package lib
Summary: lib components for the R-mclust package.
Group: Libraries

%description lib
lib components for the R-mclust package.


%prep
%setup -q -n mclust
cd %{_builddir}/mclust

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1667239402

%install
export SOURCE_DATE_EPOCH=1667239402
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/mclust/CITATION
/usr/lib64/R/library/mclust/DESCRIPTION
/usr/lib64/R/library/mclust/INDEX
/usr/lib64/R/library/mclust/Meta/Rd.rds
/usr/lib64/R/library/mclust/Meta/data.rds
/usr/lib64/R/library/mclust/Meta/features.rds
/usr/lib64/R/library/mclust/Meta/hsearch.rds
/usr/lib64/R/library/mclust/Meta/links.rds
/usr/lib64/R/library/mclust/Meta/nsInfo.rds
/usr/lib64/R/library/mclust/Meta/package.rds
/usr/lib64/R/library/mclust/Meta/vignette.rds
/usr/lib64/R/library/mclust/NAMESPACE
/usr/lib64/R/library/mclust/NEWS.md
/usr/lib64/R/library/mclust/R/mclust
/usr/lib64/R/library/mclust/R/mclust.rdb
/usr/lib64/R/library/mclust/R/mclust.rdx
/usr/lib64/R/library/mclust/data/Rdata.rdb
/usr/lib64/R/library/mclust/data/Rdata.rds
/usr/lib64/R/library/mclust/data/Rdata.rdx
/usr/lib64/R/library/mclust/doc/index.html
/usr/lib64/R/library/mclust/doc/mclust.R
/usr/lib64/R/library/mclust/doc/mclust.Rmd
/usr/lib64/R/library/mclust/doc/mclust.html
/usr/lib64/R/library/mclust/help/AnIndex
/usr/lib64/R/library/mclust/help/aliases.rds
/usr/lib64/R/library/mclust/help/figures/logo.png
/usr/lib64/R/library/mclust/help/mclust.rdb
/usr/lib64/R/library/mclust/help/mclust.rdx
/usr/lib64/R/library/mclust/help/paths.rds
/usr/lib64/R/library/mclust/html/00Index.html
/usr/lib64/R/library/mclust/html/R.css

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/mclust/libs/mclust.so
/usr/lib64/R/library/mclust/libs/mclust.so.avx2
/usr/lib64/R/library/mclust/libs/mclust.so.avx512
